apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
    - port: 3000
  selector:
    app: backend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: taeduard/demok8s:latest
          name: backend
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
              secretKeyRef:
                name: mysecret
                key: password_root
          ports:
            - containerPort: 3000
              name: backend

