apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 80
  selector:
    app: frontend

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: taeduard/demok8s:frontend
          name: frontend
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
              secretKeyRef:
                name: mysecret
                key: password_root
          ports:
            - containerPort: 80
              name: frontend

