apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", /var/lib/mysql/initScript.sh"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
              secretKeyRef:
                name: mysecret
                key: password_root
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d          
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql  
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

